### PR TITLE
Allow users to connect to server

### LINKED ISSUE #15: Any user can connect to the server

### PR DESCRIPTION
**Pull request by piecubed**

### CODE REVIEW

**Comment by piecubed** [comment]
Addresses #15

**Review by JosiahWI — APPROVED** [review]
Looks good. I didn't go through any detailed syntax, but the goroutine design should be efficient and easy to work with.

**Comment by JosiahWI** [comment]
Also, I think there are enough tests for what this PR covers, although there is a good bit more production code than probably necessary for it.

**Comment by piecubed** [comment]
Fair, I narrowed the scope of this PR to only connectivity and left in a tiny bit of messages stuff, but its not a big deal.

**Pull request merged**
